/*
 * generated by Xtext
 */
package org.buildingsmart.mvd.tmvd.ui.contentassist

import org.buildingsmart.mvd.tmvd.ui.contentassist.AbstractTextualMVDProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class TextualMVDProposalProvider extends AbstractTextualMVDProposalProvider {
}
