/*
 * generated by Xtext 2.10.0
 */
package org.buildingsmart.mvd.expressions.tests

import com.google.inject.Inject
import org.buildingsmart.mvd.expressions.expressionStrings.Expression
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.eclipse.xtext.junit4.validation.ValidationTestHelper
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(ExpressionStringsInjectorProvider)
class ExpressionStringsParsingTest {

	@Inject
	extension ParseHelper<Expression>

	@Inject
	extension ValidationTestHelper

	@Test
	def void loadModel() {
		'''
			O_PsetName [Value] = 'Pset_WallCommon' AND  O_PName [Value] = 'Thermal Transmittance' AND O_PSingleValue [Exists] = true
		'''.parse.assertNoErrors
	}

}
