/*
 * generated by Xtext
 */
package org.buildingsmart.mvd.tmvd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TextualMVDUiModule extends org.buildingsmart.mvd.tmvd.ui.AbstractTextualMVDUiModule {
	public TextualMVDUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
