/*
 * generated by Xtext
 */
package org.buildingsmart.mvd.tmvd.ui;

import org.buildingsmart.mvd.tmvd.ui.errormessages.TextualMvdSyntaxErrorMessageProvider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.parser.antlr.ISyntaxErrorMessageProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TextualMVDUiModule extends org.buildingsmart.mvd.tmvd.ui.AbstractTextualMVDUiModule
{
  public TextualMVDUiModule(AbstractUIPlugin plugin)
  {
    super(plugin);
  }

  public Class<? extends ISyntaxErrorMessageProvider> bindISyntaxErrorMessageProvider()
  {
    return TextualMvdSyntaxErrorMessageProvider.class;
  }
}
