/*
 * generated by Xtext
 */
package org.buildingsmart.mvd.tmvd;

import org.buildingsmart.mvd.tmvd.converter.ExtendedDefaultTerminalConverters;
import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class TextualMVDRuntimeModule extends org.buildingsmart.mvd.tmvd.AbstractTextualMVDRuntimeModule
{

  @Override
  public Class<? extends IValueConverterService> bindIValueConverterService()
  {
    return ExtendedDefaultTerminalConverters.class;
  }
}
