/*
 * generated by Xtext
 */
package org.buildingsmart.mvd.tmvd;

import org.buildingsmart.mvd.tmvd.converter.ExtendedDefaultTerminalConverters;
import org.buildingsmart.mvd.tmvd.generator.MvdOutputConfigurationProvider;
import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.generator.IOutputConfigurationProvider;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class TextualMVDRuntimeModule extends org.buildingsmart.mvd.tmvd.AbstractTextualMVDRuntimeModule
{

  @Override
  public Class<? extends IValueConverterService> bindIValueConverterService()
  {
    return ExtendedDefaultTerminalConverters.class;
  }

  public Class<? extends IOutputConfigurationProvider> bindIOutputConfigurationProvider()
  {
    return MvdOutputConfigurationProvider.class;
  }

//  @Override
//  public Class<? extends ITransientValueService> bindITransientValueService()
//  {
//    return TextualMVDTransientValueService.class;
//  }

}
