/*
 * generated by Xtext
 */
package org.buildingsmart.mvd.tmvd;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TextualMVDStandaloneSetup extends TextualMVDStandaloneSetupGenerated{

	public static void doSetup() {
		new TextualMVDStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

