/*
 * generated by Xtext
 */
package org.buildingsmart.mvd.tmvd.validation

import org.eclipse.xtext.validation.Check
import org.buildingsmart.mvd.mvdxml.MvdXmlPackage
import org.buildingsmart.mvd.mvdxml.ConceptTemplate

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class TextualMVDValidator extends AbstractTextualMVDValidator {

	public static val INVALID_NAME = 'invalidName'
	public static val NO_UUID = 'noUuid'

	@Check
	def checkConceptTemplateNameStartsWithCapitalLetter(ConceptTemplate conceptTemplate) {
		if (!Character.isUpperCase(conceptTemplate.name.charAt(0))) {
			warning('Name should start with a capital', MvdXmlPackage::eINSTANCE.conceptTemplate_Name,
				conceptTemplate.name, INVALID_NAME)
		}
	}

	@Check
	def checkConceptLetterHasUUID(ConceptTemplate conceptTemplate) {
		if (conceptTemplate.uuid == null) {
			warning('ConceptTemplate should have UUID defined', MvdXmlPackage::eINSTANCE.conceptTemplate_Uuid,
				conceptTemplate.uuid, NO_UUID)
		}
	}
}
